version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      APP_URL: 'localhost:3000'
      SWAPI_URL: 'http://swapi.dev/api'
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
      REDIS_DEFAULT_TTL_SECONDS: 3600
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
